service: statsLite

provider:
  name: aws
  runtime: nodejs4.3
  environment:
    DYNAMODB_TABLE: statsLiteLog
    DYNAMODB_SITE_INDEX: site-timestamp-index
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-east-1:276902424745:table/statsLiteLog"
        - "arn:aws:dynamodb:us-east-1:276902424745:table/statsLiteLog/index/*"

functions:
  log:
    handler: log.log
    events:
      - http:
          path: log
          method: post
          cors: true
  stats:
    handler: stats.stats
    events:
      - http:
          path: stats
          method: post
          cors: true
