service: statsLite

provider:
  name: aws
  runtime: nodejs4.3

functions:
  hello:
    handler: handler.hello
  log:
    handler: log.log
    events:
      - http:
          path: log
          method: post
          cors: true
